### ISSUE TITLE
option for custom history, e.g. hashHistory, memoryHistory or mock

### ISSUE THREAD

**Issue by jokeyrhyme** [remojansen/redux-bootstrap#10]
I have projects where the older-style hashHistory is more appropriate than the modern browserHistory. Further, I believe it is often suggested that we use memoryHistory for server rendering.

Also, it might expand our avenues for testing if we could similarly pass in a completely artificial history mock.

As such, it would be terrific if `bootstrap()` accepted a history option.

**Comment by jokeyrhyme** [comment]
I extracted this idea from https://github.com/remojansen/redux-bootstrap/issues/2#issuecomment-215282729

**Comment by remojansen** [comment]
Do you think that adding an new option would be enough?
```ts
bootstrap({
    container: "root",                    // optional
    initialState: {},                     // optional
    middlewares: [thunk, createLogger()], // optional
    reducers: {
        usersReducer,
        reposReducer,
    },
    routes: routes,
    history: browserHistory               // optional
});
```
By default will use `browserHistory`:
```ts
import { browserHistory } from "react-router";
```

**Comment by jokeyrhyme** [comment]
That's pretty much the approach I'd be taking, including keeping the current default behaviour as you suggest.

**Comment by remojansen** [comment]
I'm working on [an example](https://github.com/remojansen/redux-bootstrap-example) to try to find issues.

I spot one. If your app is in a sub directory you need to use the `basename` setting:
```
import { createHistory } from 'history';
import { Router, useRouterHistory } from 'react-router';

const browserHistory = useRouterHistory(createHistory)({
   basename: '/whatever'
});
```
So I think we also need:
```ts
bootstrap({
    container: "root",                    // optional
    initialState: {},                     // optional
    middlewares: [thunk, createLogger()], // optional
    reducers: {
        usersReducer,
        reposReducer,
    },
    routes: routes,
    basename: "/whatever",               // optional (uses browserHistory)
    history: browserHistory               // optional
});
```

**Comment by remojansen** [comment]
@jokeyrhyme I have created [a gitter chat room](https://gitter.im/remojansen/redux-bootstrap) so we can do better planning. I have added you as contributor of this repo so you can push but please try to work on a fork and send PRs I will code review them. I will do the same so you can then code review my PRs.

**Comment by jokeyrhyme** [comment]
I've got a few projects using the [davezuko/react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit), and they have a compile-time webpack(?) transform that replaces `__BASENAME__` with a value from the environment.

- https://github.com/davezuko/react-redux-starter-kit/blob/master/src/main.js#L13
- https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js#L80

I think passing it all in the one place as you suggest is probably better. And even if someone does have such a transform, they can use the proposed configuration to pass it through easily.

**Comment by remojansen** [comment]
I agree with you, the users will still be able to do the following:
```
bootstrap({
    container: "root",                    // optional
    initialState: {},                     // optional
    middlewares: [thunk, createLogger()], // optional
    reducers: {
        usersReducer,
        reposReducer,
    },
    routes: routes,
    basename: __BASENAME__,               // optional (uses browserHistory)
    history: browserHistory               // optional
});
```
