### ISSUE TITLE
syncHistoryWithStore susceptible to constant mutation issue

### ISSUE THREAD

**Issue by jokeyrhyme** [remojansen/redux-bootstrap#2]
Referring to this line:
- https://github.com/remojansen/redux-bootstrap/blob/master/src/index.tsx#L52

Which looks like it might be susceptible to this issue:
- https://github.com/reactjs/react-router-redux/issues/314

## Expected Behavior

`syncHistoryWithStore()` should result in a history that efficiently synchronises its state with the Redux store, only making changes when the history state has changed.

## Current Behavior

It currently defines a selector that returns a brand new `Object` each time, ~~which means the root Redux store state object will be different, which means the whole Redux state tree is being invalidated over and over and over~~ which means the router (via `history.listen()`) believes navigation has been requested via the store, even for store changes that have nothing to do with navigation.

## Possible Solution

- https://github.com/reactjs/react-router-redux/issues/314#issuecomment-190678756
- https://github.com/reactjs/react-router-redux/issues/301
- https://github.com/gajus/redux-immutable/issues/23

## Steps to Reproduce (for bugs)

Attach a listener to the store with `store.subscribe()` so that you can see that the store is being updated constantly due to the use of `syncHistoryWithStore()`.

**Comment by jokeyrhyme** [comment]
There might be a cleaner solution that involves [reselect](https://github.com/reactjs/reselect), but that would mean an extra dependency. /shrug

**Comment by remojansen** [comment]
Hi @jokeyrhyme thanks a lot for reporting this issue. Would you like to contribute. If not that is fine, I can take care of it.

**Comment by jokeyrhyme** [comment]
I'll put together a PR for this in the next few days, if I get time.

**Comment by jokeyrhyme** [comment]
Okay, so I'm working with an non-bootstrapped example where I've subscribed to the sync'ed `history` like so:

```js
const history = syncHistoryWithStore(/* ... */);
history.listen(() => console.log('history'));
```

Whenever the Redux store state changes, the history listener is called (I see the console messages). If I have an action triggered by an `<input onChange={() => dispatchAction()} />`, then the listener is called on every keypress.

When I've applied the fix, the only time the history listener is called is when navigation has occurred. Other parts of the Redux store state can change without triggering the history listener. This is the desired effect.

I'm having issues trying to test this within react-bootstrap, however, because we don't return the sync'ed `history` object. Any ideas?

**Comment by remojansen** [comment]
Hi @jokeyrhyme thanks for helping with this. 

A workmate was using this and he suggested that there should be a way to access not only the store but the root component. Now you need to access the history so I have done a change to allow access to all this entities.

```ts
const result = bootstrap({/* ... */});
```
The result objec is an implementation of the following interface:
```ts
interface BootstrapResult {
    store: Redux.Store,
    history: ReactRouterRedux.ReactRouterReduxHistory,
    root: JSX.Element
}
```
This change has been merged into master.

**Comment by jokeyrhyme** [comment]
I've been looking at this issue and an option to provide a custom history (e.g. hashHistory or memoryHistory instead). It has been difficult writing tests for this, because it is not expected that `bootstrap()` be called multiple times in the same context.

I'm pretty sure there's a way to load multiple tests into karma in a way that gives each test its own context, but I haven't had much time to figure this out yet. Any pointers?

Or, alternatively, do you think it would be appropriate to for `bootstrap()` to also provide a `teardown()` function that destroys everything?

**Comment by remojansen** [comment]
Thanks a lot for helping out. I had this same problem when I was testing. I will see if I can do something. I have created an issue to track it https://github.com/remojansen/redux-bootstrap/issues/11
