### ISSUE TITLE
redux-immutable necessary?

### ISSUE THREAD

**Issue by kennetpostigo** [remojansen/redux-bootstrap#4]
Is redux-immutable necessary to use with redux? I've used redux + immutable for some time now and never needed to integrate redux-immutable even when using combine reducers. I think redux fixed this after a certain version number.

**Comment by remojansen** [comment]
Do you have a link where I can research it? As far as I know redux-immutable is needed.

**Comment by kennetpostigo** [comment]
Let me see if I can find it in the releases tab.

**Comment by jokeyrhyme** [comment]
If you just use the 1st-party `combineReducers()` helper, then your state root will be a plain Object. If you use the 3rd-party redux-immutable version, then your state root will be an Immutable.js Map.

I think this comes down to basic preference. Do you want to remember that your state root is different to everything nested beneath it? Or do you want to be able to consistently use `state.get()` everywhere?

I have tested this though, and as long as you carefully remember the difference, it seems like everything works as expected. I think I'm going to keep using redux-immutable, personally, just for consistency.

**Comment by remojansen** [comment]
I would recommend to use `redux-immutable`as well for consistency as @jokeyrhyme has suggested. This project uses an immutable map as the default state. Using an state that has some immutable properties and others non-immutable properties would be potentially confusing. Is better to assume that everything is immutable.
